[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_d_app = "i2oJay4YSQQB4A9eH7uDZ9V57VszTH7VN6sASHaiNiv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"  
wallet = "~/.config/solana/id.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
